### PR TITLE
GitHub/waffle Process Documentation

### PR DESCRIPTION
**Pull request by jim-v**
This is based on an email by @rohbotics, with details of testing a PR added.

### CODE REVIEW

**Comment by jim-v** [comment]
Fixes #70

**Review by davecrawley — APPROVED** [review]
Looks good! Made a slight change to the document to say that documentation can commit to the main branch but code should not.

**Review by davecrawley — COMMENTED** [review]
I am also going to try this tomorrow on the robot, once I have had a chance to try it then I will merge it.

**Comment by jimvaughan** [comment]
@davecrawley , we should wait for all the reviews before merging

**Review by rohbotics — APPROVED** [review]

**Pull request merged**
