### PR TITLE
Update git workflow with more detail

### PR DESCRIPTION
**Pull request by rohbotics**
This more closely reflects the current workflow.

### CODE REVIEW

**Review by waynegramlich — COMMENTED** [review]
Generally speaking, the workflow described makes sense.  However, the actual mechanics of each step are not clear at all.  For example step 1, "Make an issue describing...", how is that done?  Is there github documentation that explains each of these steps?  Simple links to github documentation would probably solve all of my issues.

**Comment by rohbotics** [comment]
Thanks for the review, updated with links to github docs.

**Comment by waynegramlich** [comment]
The newest changes look just about right.  I'm too groggy right now to close out this request.  I'll try and follow the links you provided to properly close this issue some time tomorrw.

**Comment by rohbotics** [comment]
@waynegramlich bump

**Pull request merged**
